name: CI
on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  unit:
    name: ubuntu-latest jdk-11
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mvn clean install
        run: |
          mvn clean install
 
